services:
  zeek:
    image: zeek/zeek:7.1
    volumes:
      - zeek-logs:/logs
      - ./zeek/local.zeek:/local.zeek
    command: |
      /bin/sh -c `mkdir -p /logs && cd logs
      zkg install geoip-conn --force
      zeek -C -i eth0 /local.zeek`
    network_mode: host
    cap_add:
      - NET_ADMIN
  grafana:
    image: grafana/grafana:11.5.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/main.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
  loki:
    image: grafana/loki:3.3.2
    volumes:
      - loki-data:/data/loki
  alloy:
    image: grafana/alloy:v1.6.1
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - zeek-logs:/logs
volumes:
  zeek-logs:
  loki-data:
  grafana-data: