{
 "title": "Zeek",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Connection Location",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/logs/conn.log\"} |= `geo` "
    }
   ]
  },
  {
   "title": "SSL Server Name",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sort(sum by(server_name) (count_over_time({filename=\"/logs/ssl.log\"} | json | line_format `{{.server_name}}` [$__auto]))) ",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sort(sum by(id_resp_h) (count_over_time({filename=\"/logs/conn.log\"} | json | line_format `{{.id_resp_h}}` [$__auto]))) ",
     "legendFormat": "{{id_resp_h}}"
    }
   ]
  },
  {
   "title": "DNS Query",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sort(sum by(query) (count_over_time({filename=\"/logs/dns.log\"} |= `query` | json | line_format `{{.query}}` [$__auto]))) ",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Http Connection",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sort(sum by(id_resp_h) (count_over_time({filename=\"/logs/http.log\"} | json | line_format `{{.id_resp_h}}` [$__auto]))) ",
     "legendFormat": "{{id_resp_h}}"
    }
   ]
  }
 ]
}